name: luarocks

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "luajit", "luajit-openresty"]

    env:
      ROCKSPEC: meta-scm-0.rockspec

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4

    - name: dependencies
      run: |
        luarocks install busted

    - name: make
      run: luarocks --dev make

    - name: busted
      run: luarocks test

    - name: publish
      if: success()
      continue-on-error: true
      run: luarocks upload ${{ env.ROCKSPEC }} --api-key=${{ env.LUAROCKS_API_KEY }}
      env:
        LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
